spring:
  application:
    name: "inventoryService"
  data:
    mongodb:
      uri: "mongodb+srv://amrit:indira@cluster0.8saiim6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "tshirtshop"