spring:
  application:
    name: "inventoryService"
  data:
    mongodb:
      uri: ${MONGODBURI}
#      uri: "mongodb+srv://amrit:indira@cluster0.8saiim6.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      database: "tshirtshop"
logging:
  level:
    com.ecommerce.inventoryservice: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083