spring:
  application:
    name: gatewayserver
  security:
    enabled: false
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lowerCaseServiceId: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

sever:
  port: 8082